import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (!context) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
};

export const translations = {
    en: {
        // Navigation
        dashboard: "Dashboard",
        analytics: "Analytics",
        masterData: "Master Data",
        crm: "CRM",
        sales: "Sales",
        production: "Production",
        inventory: "Inventory",
        quality: "Quality",
        purchasing: "Purchasing",
        supplyChain: "Supply Chain",
        projects: "Projects",
        finance: "Finance",
        reports: "Reports",
        maintenance: "Maintenance",
        hrPayroll: "HR & Payroll",
        zatca: "ZATCA E-Invoice",
        approvals: "Approvals",
        adminCenter: "Admin Center",
        fixedAssets: "Fixed Assets",
        assetVerification: "Asset Verification",
        assetLifecycle: "Asset Lifecycle",
        depreciationReports: "Depreciation Reports",
        costing: "Costing",
        notifications: "Notifications",
        assetScanner: "Asset Scanner",
        
        // Common Actions
        new: "New",
        create: "Create",
        edit: "Edit",
        delete: "Delete",
        save: "Save",
        cancel: "Cancel",
        close: "Close",
        search: "Search",
        filter: "Filter",
        export: "Export",
        print: "Print",
        download: "Download",
        upload: "Upload",
        refresh: "Refresh",
        submit: "Submit",
        approve: "Approve",
        reject: "Reject",
        send: "Send",
        back: "Back",
        next: "Next",
        previous: "Previous",
        viewAll: "View All",
        markAllRead: "Mark all read",
        
        // Status
        active: "Active",
        inactive: "Inactive",
        pending: "Pending",
        approved: "Approved",
        rejected: "Rejected",
        completed: "Completed",
        cancelled: "Cancelled",
        draft: "Draft",
        inProgress: "In Progress",
        overdue: "Overdue",
        scheduled: "Scheduled",
        
        // Common Fields
        code: "Code",
        name: "Name",
        description: "Description",
        date: "Date",
        status: "Status",
        amount: "Amount",
        quantity: "Quantity",
        price: "Price",
        total: "Total",
        customer: "Customer",
        vendor: "Vendor",
        material: "Material",
        product: "Product",
        location: "Location",
        department: "Department",
        priority: "Priority",
        type: "Type",
        
        // Master Data
        materials: "Materials",
        customers: "Customers",
        vendors: "Vendors",
        newMaterial: "New Material",
        newCustomer: "New Customer",
        newVendor: "New Vendor",
        materialCode: "Material Code",
        materialName: "Material Name",
        materialType: "Material Type",
        unitOfMeasure: "Unit of Measure",
        unitPrice: "Unit Price",
        unitCost: "Unit Cost",
        currentStock: "Current Stock",
        reorderPoint: "Reorder Point",
        downloadTemplate: "Download Template",
        uploadExcel: "Upload Excel",
        
        // Fixed Assets
        assetNumber: "Asset Number",
        assetName: "Asset Name",
        assetTag: "Asset Tag",
        assetClass: "Asset Class",
        acquisitionDate: "Acquisition Date",
        acquisitionCost: "Acquisition Cost",
        netBookValue: "Net Book Value",
        accumulatedDepreciation: "Accumulated Depreciation",
        usefulLife: "Useful Life",
        depreciationMethod: "Depreciation Method",
        salvageValue: "Salvage Value",
        responsiblePerson: "Responsible Person",
        
        // Purchasing
        purchaseRequisition: "Purchase Requisition",
        rfq: "Request for Quotation",
        purchaseOrder: "Purchase Order",
        goodsReceiptNote: "Goods Receipt Note",
        vendorInvoice: "Vendor Invoice",
        threeWayMatch: "3-Way Match",
        
        // Sales
        quotation: "Quotation",
        salesOrder: "Sales Order",
        delivery: "Delivery",
        invoice: "Invoice",
        salesReturn: "Sales Return",
        
        // Production
        productionOrder: "Production Order",
        bom: "Bill of Materials",
        routing: "Routing",
        workCenter: "Work Center",
        
        // Quality
        inspectionLot: "Inspection Lot",
        qualityControl: "Quality Control",
        nonConformance: "Non-Conformance",
        capa: "CAPA",
        
        // Inventory
        stockMovement: "Stock Movement",
        stockTransfer: "Stock Transfer",
        cycleCount: "Cycle Count",
        stockLevel: "Stock Level",
        
        // Notifications
        unreadNotifications: "Unread Notifications",
        readNotifications: "Read Notifications",
        noNotifications: "No notifications",
        notificationSettings: "Notification Settings",
        
        // Messages
        loading: "Loading...",
        noData: "No data available",
        success: "Success",
        error: "Error",
        warning: "Warning",
        confirm: "Confirm",
        areYouSure: "Are you sure?",
        savedSuccessfully: "Saved successfully",
        deletedSuccessfully: "Deleted successfully",
        operationSuccessful: "Operation successful",
        operationFailed: "Operation failed",
        
        // Company
        companyName: "HORIZON",
        companyTagline: "Powering Your Digital Future",

        // Projects
        projectsServices: "Projects & Services",
        activeProjects: "Active Projects",
        revenue: "Revenue",
        unbilled: "Unbilled",
        utilization: "Utilization",
        avgMargin: "Avg Margin",
        atRisk: "At Risk",
        timesheets: "Timesheets",
        expenses: "Expenses",
        milestones: "Milestones",
        invoices: "Invoices",
        resources: "Resources",

        // Sales & Distribution
        salesDistribution: "Sales & Distribution",
        hitRate: "Hit Rate",
        otif: "OTIF",
        creditHold: "Credit Hold",
        returns: "Returns",
        quotations: "Quotations",
        orders: "Orders",
        deliveries: "Deliveries",
        services: "Services",

        // Manufacturing
        manufacturing: "Manufacturing & Production",
        activeProduction: "Active Production",
        avgYield: "Average Yield",
        availableWorkCenters: "Available Work Centers",
        variancesPending: "Variances Pending",
        productionOrders: "Production Orders",
        boms: "BOMs",
        routings: "Routings",
        workCenters: "Work Centers",
        variances: "Variances",
        standardCosts: "Standard Costs",

        // Quality Management
        qualityManagement: "Quality Management",
        firstPassYield: "First Pass Yield",
        rejectedLots: "Rejected Lots",
        openNCs: "Open NCs",
        coasIssued: "COAs Issued",
        inspectionLots: "Inspection Lots",
        nonConformances: "Non-Conformances",
        coas: "COA",
        qcPlans: "QC Plans",

        // Procurement
        procurement: "Procurement",
        pendingPRs: "Pending PRs",
        activePOs: "Active POs",
        totalSpend: "Total Spend",
        pendingMatches: "Pending Matches",
        requisitions: "Requisitions",
        rfqs: "RFQs",
        pos: "Purchase Orders",
        grns: "GRNs",
        vendorInvoices: "Vendor Invoices",

        // Maintenance Management
        maintenanceManagement: "Maintenance Management",
        openWorkOrders: "Open Work Orders",
        pmCompliance: "PM Compliance",
        mttr: "MTTR (Hours)",
        criticalDown: "Critical Down",
        lowStockParts: "Low Stock Parts",
        totalCost: "Total Cost",
        workOrders: "Work Orders",
        pmPlans: "PM Plans",
        equipment: "Equipment",
        spareParts: "Spare Parts",
        downtimes: "Downtimes",
        consumptions: "Consumptions",

        // Finance & Accounting
        financeAccounting: "Finance & Accounting",
        totalAROutstanding: "Total AR Outstanding",
        totalAPOutstanding: "Total AP Outstanding",
        overdueAR: "Overdue AR",
        fixedAssetsNBV: "Fixed Assets NBV",
        gl: "GL",
        ar: "AR",
        ap: "AP",
        cashBank: "Cash/Bank",

        // HR & Payroll
        hrPayrollKSA: "HR & Payroll (KSA)",
        activeEmployees: "Active Employees",
        saudizationRate: "Saudization Rate",
        pendingLeaves: "Pending Leaves",
        activeLoans: "Active Loans",
        employees: "Employees",
        leaves: "Leave Requests",
        payroll: "Payroll",
        loansAdvances: "Loans/Advances",
        endOfService: "End of Service",

        // Analytics specific
        analyticsBI: "Business Intelligence & Analytics",
        kpisDashboardsInsights: "KPIs, Dashboards & Performance Insights",
        dateRange: "Date Range",
        branch: "Branch",
        last7Days: "Last 7 Days",
        last30Days: "Last 30 Days",
        last90Days: "Last 90 Days",
        ytd: "Year to Date",
        lastYear: "Last Year",
        allBranches: "All Branches",
        riyadh: "Riyadh",
        jeddah: "Jeddah",
        dammam: "Dammam",
        executive: "Executive",
        totalRevenue: "Total Revenue",
        grossProfit: "Gross Profit",
        stockValue: "Stock Value",
        margin: "margin",
        turnover: "turnover",
        efficiency: "efficiency",
        dso: "DSO (Days)",
        dsoFull: "Days Sales Outstanding",
        dpo: "DPO (Days)",
        dpoFull: "Days Payable Outstanding",
        qualityRate: "Quality Rate",
        saudization: "Saudization",
        saudi: "Saudi",
        revenueTrend: "Revenue Trend (Last 6 Months)",
        topProductsByRevenue: "Top 5 Products by Revenue",
        inventoryAging: "Inventory Aging",
        arAgingAnalysis: "AR Aging Analysis",
        totalOrders: "Total Orders",
        avgOrderValue: "Avg Order Value",
        perOrder: "Per order",
        pendingOrders: "Pending Orders",
        awaitingConfirmation: "Awaiting confirmation",
        delivered: "Delivered",
        completedOrders: "Completed orders",
        salesByMonth: "Sales by Month",
        salesByStatus: "Sales by Status",
        count: "Count",
        unitsSold: "units sold",
        totalStockValue: "Total Stock Value",
        items: "items",
        stockTurnover: "Stock Turnover",
        annualTurnover: "Annual turnover",
        slowMoving: "Slow Moving",
        over90Days: ">90 days old",
        lowStockItems: "Low Stock Items",
        needReorder: "Need reorder",
        inventoryAgingDistribution: "Inventory Aging Distribution",
        stockValueByCategory: "Stock Value by Category",
        value: "Value",
        productionEfficiency: "Production Efficiency",
        outputVsPlanned: "Output vs planned",
        totalProduced: "Total Produced",
        units: "Units",
        productionByStatus: "Production by Status",
        productionQuantityByProduct: "Production Quantity by Product",
        totalPurchases: "Total Purchases",
        avgPOValue: "Avg PO Value",
        perPO: "Per PO",
        payableOutstanding: "Payable outstanding",
        pendingPOs: "Pending POs",
        awaitingApproval: "Awaiting approval",
        purchaseByVendor: "Purchase by Vendor",
        apAging: "AP Aging",
        salesOutstanding: "Sales outstanding",
        revenueVsCosts: "Revenue vs Costs",
        costs: "Costs",
        profit: "Profit",
        arVsAp: "AR vs AP",
        accountsReceivable: "Accounts Receivable",
        accountsPayable: "Accounts Payable",
        cashFlowIndicators: "Cash Flow Indicators",
        workingCapital: "Working Capital",
        cashConversionCycle: "Cash Conversion Cycle",
        days: "days",
        currentRatio: "Current Ratio",
        quickRatio: "Quick Ratio",
        projectMargin: "Project Margin",
        grossMargin: "Gross margin",
        employeesByDepartment: "Employees by Department",
        nationalityDistribution: "Nationality Distribution",
        nonSaudi: "Non-Saudi",
        projectPerformance: "Project Performance",
        complete: "complete",
        
        // Projects & Services
        newProject: "New Project",
        newTask: "New Task",
        newTimesheet: "New Timesheet",
        newExpense: "New Expense",
        newMilestone: "New Milestone",
        resourceAllocations: "Resource Allocations",
        projectExpenses: "Project Expenses",
        projectMilestones: "Project Milestones",
        projectTasks: "Project Tasks",
        allocateResource: "Allocate Resource",
        bulkAllocate: "Bulk Allocate",
        
        // AI Assistant
        aiAssistantAnalytics: "AI Assistant & Analytics",
        aiInsightsDesc: "Get insights, ask questions, and let AI help you manage your business",
        chatAssistant: "Chat Assistant",
        aiInsights: "AI Insights",
        newChat: "New Chat",
        erpAssistant: "ERP Assistant",
        messages: "messages",
        howCanIHelp: "How can I help you today?",
        askMeAnything: "Ask me anything about your business data, reports, or let me help you create and manage records.",
        showSalesPerformance: "Show sales performance",
        checkInventoryLevels: "Check inventory levels",
        viewPendingApprovals: "View pending approvals",
        askAnything: "Ask me anything about your business...",
        noConversationSelected: "No conversation selected",
        createChatToStart: "Create a new chat to get started",
        startNewChat: "Start New Chat",
        
        // KPI Dashboard
        kpiDashboard: "KPI Dashboard",
        trackMonitorKPIs: "Track and monitor key performance indicators",
        addKPI: "Add KPI",
        onTarget: "On Target",
        atRisk: "At Risk",
        offTarget: "Off Target",
        avgAchievement: "Avg Achievement",
        ofKPIs: "of KPIs",
        needsAttention: "Needs attention",
        requiresAction: "Requires action",
        overallPerformance: "Overall performance",
        allKPIs: "All KPIs",
        allCategories: "All Categories",
        financialKPIs: "Financial KPIs",
        operationalKPIs: "Operational KPIs",
        customerKPIs: "Customer KPIs",
        employeeKPIs: "Employee KPIs",
        qualityKPIs: "Quality KPIs",
        supplyChainKPIs: "Supply Chain KPIs",
        kpiName: "KPI Name",
        category: "Category",
        owner: "Owner",
        target: "Target",
        actual: "Actual",
        achievement: "Achievement",
        trend: "Trend",
        updateFreq: "Update Freq",
        
        // Master Data Management
        masterDataMgmt: "Master Data Management",
        manageMasterData: "Manage materials, customers, vendors, salesmen & hierarchies",
        refreshAll: "Refresh All",
        totalMaterials: "Total Materials",
        groups: "groups",
        totalCustomers: "Total Customers",
        salesmen: "Salesmen",
        unitConversions: "Unit Conversions",
        multiUOM: "Multi-UOM enabled",
        materialsItems: "Materials & Items Master",
        template: "Template",
        excelUpload: "Excel Upload",
        newMaterial: "New Material",
        customerMaster: "Customer Master (Linked to Salesman)",
        newCustomer: "New Customer",
        vendorMaster: "Vendor Master",
        newVendor: "New Vendor",
        salesmenMaster: "Salesmen Master",
        newSalesman: "New Salesman",
        materialGroups: "Material Groups",
        newGroup: "New Group",
        materialSubGroups: "Material Sub-Groups",
        newSubGroup: "New Sub-Group",
        unitConversionsTitle: "Unit Conversions (Pcs ↔ Bundle ↔ Tons)",
        newConversion: "New Conversion",
        
        // Coil Management
        coilManagementSlitting: "Coil Management & Slitting",
        trackCoilsDesc: "Track and manage raw material coils and slitting operations",
        totalCoils: "Total Coils",
        allRegisteredCoils: "All registered coils",
        available: "Available",
        readyToUse: "Ready to use",
        totalWeight: "Total Weight",
        currentStock: "Current stock",
        reserved: "Reserved",
        forProduction: "For production",
        qcPending: "QC Pending",
        awaitingInspection: "Awaiting inspection",
        coilInventory: "Coil Inventory",
        slittingOperations: "Slitting Operations",
        history: "History",
        slitCoil: "Slit Coil",
        registerCoil: "Register Coil",
        coilHistory: "Coil History & Traceability",
        
        // Supply Chain
        supplyChainMgmt: "Supply Chain Management",
        endToEndVisibility: "End-to-end visibility of material and product flow",
        procurement: "Procurement",
        distribution: "Distribution",
        recentPurchaseOrders: "Recent Purchase Orders",
        recentSalesOrders: "Recent Sales Orders",
        
        // Costing
        costManagement: "Cost Management",
        productCostingDesc: "Product Costing, Variance Analysis & Job Costing",
        activeProductCosts: "Active Product Costs",
        avgCost: "Avg",
        unit: "unit",
        totalActualCosts: "Total Actual Costs",
        costRecords: "cost records",
        unfavorableVariances: "Unfavorable Variances",
        averageMargin: "Average Margin",
        acrossProducts: "Across",
        products: "products",
        productCosts: "Product Costs",
        actualCosts: "Actual Costs",
        costPools: "Cost Pools",
        overheadRates: "Overhead Rates",
        jobCosts: "Job Costs",
        productCosting: "Product Costing",
        calculateProductCost: "Calculate Product Cost",
        actualCostRecords: "Actual Cost Records",
        costVarianceAnalysis: "Cost Variance Analysis",
        newCostPool: "New Cost Pool",
        newOverheadRate: "New Overhead Rate",
        jobCosting: "Job Costing",
        
        // Treasury Management
        treasuryMgmt: "Treasury Management",
        cashFlowForecastingDesc: "Cash Flow Forecasting & Liquidity Management",
        
        // Asset Lifecycle
        assetLifecycleMgmt: "Asset Lifecycle Management",
        trackAssetDisposalDesc: "Track asset disposal, retirement, ROI and lifecycle analytics",
        exportCSV: "Export CSV",
        printReport: "Print Report",
        filters: "Filters",
        reset: "Reset",
        assetClass: "Asset Class",
        allClasses: "All Classes",
        machinery: "Machinery",
        equipment: "Equipment",
        vehicles: "Vehicles",
        computers: "Computers",
        furniture: "Furniture",
        disposalType: "Disposal Type",
        allTypes: "All Types",
        sale: "Sale",
        scrap: "Scrap",
        donation: "Donation",
        tradeIn: "Trade-In",
        writeOff: "Write-Off",
        dateFrom: "Date From",
        dateTo: "Date To",
        yearFrom: "Year From",
        yearTo: "Year To",
        activeAssets: "Active Assets",
        currentlyInUse: "Currently in use",
        disposedAssets: "Disposed Assets",
        pendingApproval: "pending approval",
        disposalValue: "Disposal Value",
        transactions: "transactions",
        totalGainLoss: "Total Gain/Loss",
        netGain: "Net gain",
        netLoss: "Net loss",
        averageROI: "Average ROI",
        onDisposedAssets: "On disposed assets",
        byType: "By Type",
        byYear: "By Year",
        roiAnalysis: "ROI Analysis",
        lifecycle: "Lifecycle",
        details: "Details",
        disposalByType: "Disposal by Type",
        breakdown: "Breakdown",
        assets: "assets",
        disposalTrend: "Disposal Trend by Year",
        roiDistribution: "ROI Distribution",
        roiCategories: "ROI Categories",
        assetAgeVsMaintenance: "Asset Age vs Maintenance Cost",
        insights: "Insights",
        disposalTransactions: "Disposal Transactions",
        
        // Approval Workflows
        approvalWorkflowConfig: "Approval Workflow Configuration",
        configureMultiLevelDesc: "Configure multi-level approval chains for business documents",
        workflowBuilder: "Workflow Builder",
        allRules: "All Rules",
        configureNewWorkflow: "Configure New Workflow",
        newRule: "New Rule",
        allApprovalMatrixRules: "All Approval Matrix Rules",
        documentType: "Document Type",
        amountRange: "Amount Range (SAR)",
        level: "Level",
        requiredRole: "Required Role",
        settings: "Settings",
        mandatory: "Mandatory",
        parallel: "Parallel",
        notify: "Notify",
        approvalLevels: "Approval Levels",
        
        // HR
        hr: "HR",
        
        // Additional common terms
        overview: "Overview",
        financial: "Financial",
        operational: "Operational",
        employee: "Employee",
        
        // Manufacturing & Production (additional)
        bomItems: "BOM Items",
        operations: "Operations",
        materialIssue: "Material Issue",
        productionConfirmation: "Production Confirmation",
        
        // Demand Planning
        forecastAccuracy: "Forecast Accuracy",
        demandForecast: "Demand Forecast",
        forecastMethod: "Forecast Method",
        forecastedQuantity: "Forecasted Quantity",
        actualDemand: "Actual Demand",
        
        // Treasury Management (additional)
        cashPosition: "Cash Position",
        cashFlowForecast: "Cash Flow Forecast",
        liquidityRatio: "Liquidity Ratio",
        inflows: "Inflows",
        outflows: "Outflows",
        
        // Depreciation Reports (additional)
        depreciationSchedule: "Depreciation Schedule",
        assetRegister: "Asset Register",
        monthlyDepreciation: "Monthly Depreciation",
        yearlyDepreciation: "Yearly Depreciation",
        
        // HR & Payroll (additional)
        payslip: "Payslip",
        attendanceRegister: "Attendance Register",
        leaveBalance: "Leave Balance",
        endOfServiceBenefit: "End of Service Benefit",
        wps: "WPS",
        gosi: "GOSI",
        
        // ZATCA (additional)
        zatcaCompliant: "ZATCA Compliant",
        einvoicing: "E-Invoicing",
        qrCode: "QR Code",
        submissionStatus: "Submission Status",
        clearanceStatus: "Clearance Status"
    },
    ar: {
        // Navigation
        dashboard: "لوحة التحكم",
        analytics: "التحليلات",
        masterData: "البيانات الرئيسية",
        crm: "إدارة العملاء",
        sales: "المبيعات",
        production: "الإنتاج",
        inventory: "المخزون",
        quality: "الجودة",
        purchasing: "المشتريات",
        supplyChain: "سلسلة الإمداد",
        projects: "المشاريع",
        finance: "المالية",
        reports: "التقارير",
        maintenance: "الصيانة",
        hrPayroll: "الموارد البشرية والرواتب",
        zatca: "الفواتير الإلكترونية",
        approvals: "الموافقات",
        adminCenter: "مركز الإدارة",
        fixedAssets: "الأصول الثابتة",
        assetVerification: "التحقق من الأصول",
        assetLifecycle: "دورة حياة الأصول",
        depreciationReports: "تقارير الإهلاك",
        costing: "التكاليف",
        notifications: "الإشعارات",
        assetScanner: "ماسح الأصول",
        
        // Common Actions
        new: "جديد",
        create: "إنشاء",
        edit: "تعديل",
        delete: "حذف",
        save: "حفظ",
        cancel: "إلغاء",
        close: "إغلاق",
        search: "بحث",
        filter: "تصفية",
        export: "تصدير",
        print: "طباعة",
        download: "تحميل",
        upload: "رفع",
        refresh: "تحديث",
        submit: "إرسال",
        approve: "موافقة",
        reject: "رفض",
        send: "إرسال",
        back: "رجوع",
        next: "التالي",
        previous: "السابق",
        viewAll: "عرض الكل",
        markAllRead: "وضع علامة مقروء للكل",
        
        // Status
        active: "نشط",
        inactive: "غير نشط",
        pending: "قيد الانتظار",
        approved: "موافق عليه",
        rejected: "مرفوض",
        completed: "مكتمل",
        cancelled: "ملغى",
        draft: "مسودة",
        inProgress: "قيد التنفيذ",
        overdue: "متأخر",
        scheduled: "مجدول",
        
        // Common Fields
        code: "الرمز",
        name: "الاسم",
        description: "الوصف",
        date: "التاريخ",
        status: "الحالة",
        amount: "المبلغ",
        quantity: "الكمية",
        price: "السعر",
        total: "المجموع",
        customer: "العميل",
        vendor: "المورد",
        material: "المادة",
        product: "المنتج",
        location: "الموقع",
        department: "القسم",
        priority: "الأولوية",
        type: "النوع",
        
        // Master Data
        materials: "المواد",
        customers: "العملاء",
        vendors: "الموردين",
        newMaterial: "مادة جديدة",
        newCustomer: "عميل جديد",
        newVendor: "مورد جديد",
        materialCode: "رمز المادة",
        materialName: "اسم المادة",
        materialType: "نوع المادة",
        unitOfMeasure: "وحدة القياس",
        unitPrice: "سعر الوحدة",
        unitCost: "تكلفة الوحدة",
        currentStock: "المخزون الحالي",
        reorderPoint: "نقطة إعادة الطلب",
        downloadTemplate: "تحميل النموذج",
        uploadExcel: "رفع ملف إكسل",
        
        // Fixed Assets
        assetNumber: "رقم الأصل",
        assetName: "اسم الأصل",
        assetTag: "علامة الأصل",
        assetClass: "فئة الأصل",
        acquisitionDate: "تاريخ الحيازة",
        acquisitionCost: "تكلفة الحيازة",
        netBookValue: "صافي القيمة الدفترية",
        accumulatedDepreciation: "الإهلاك المتراكم",
        usefulLife: "العمر الإنتاجي",
        depreciationMethod: "طريقة الإهلاك",
        salvageValue: "قيمة الإنقاذ",
        responsiblePerson: "الشخص المسؤول",
        
        // Purchasing
        purchaseRequisition: "طلب الشراء",
        rfq: "طلب عرض أسعار",
        purchaseOrder: "أمر الشراء",
        goodsReceiptNote: "إشعار استلام البضائع",
        vendorInvoice: "فاتورة المورد",
        threeWayMatch: "المطابقة الثلاثية",
        
        // Sales
        quotation: "عرض سعر",
        salesOrder: "أمر مبيعات",
        delivery: "تسليم",
        invoice: "فاتورة",
        salesReturn: "مرتجع مبيعات",
        
        // Production
        productionOrder: "أمر إنتاج",
        bom: "قائمة المواد",
        routing: "مسار الإنتاج",
        workCenter: "مركز العمل",
        
        // Quality
        inspectionLot: "دفعة الفحص",
        qualityControl: "مراقبة الجودة",
        nonConformance: "عدم المطابقة",
        capa: "الإجراءات التصحيحية والوقائية",
        
        // Inventory
        stockMovement: "حركة المخزون",
        stockTransfer: "نقل المخزون",
        cycleCount: "الجرد الدوري",
        stockLevel: "مستوى المخزون",
        
        // Notifications
        unreadNotifications: "الإشعارات غير المقروءة",
        readNotifications: "الإشعارات المقروءة",
        noNotifications: "لا توجد إشعارات",
        notificationSettings: "إعدادات الإشعارات",
        
        // Messages
        loading: "جاري التحميل...",
        noData: "لا توجد بيانات",
        success: "نجح",
        error: "خطأ",
        warning: "تحذير",
        confirm: "تأكيد",
        areYouSure: "هل أنت متأكد؟",
        savedSuccessfully: "تم الحفظ بنجاح",
        deletedSuccessfully: "تم الحذف بنجاح",
        operationSuccessful: "تمت العملية بنجاح",
        operationFailed: "فشلت العملية",
        
        // Company
        companyName: "HORIZON",
        companyTagline: "Powering Your Digital Future",

        // Projects
        projectsServices: "المشاريع والخدمات",
        activeProjects: "المشاريع النشطة",
        revenue: "الإيرادات",
        unbilled: "غير مفوتر",
        utilization: "معدل الاستغلال",
        avgMargin: "متوسط الهامش",
        atRisk: "معرض للخطر",
        timesheets: "جداول العمل",
        expenses: "المصروفات",
        milestones: "المعالم",
        invoices: "الفواتير",
        resources: "الموارد",

        // Sales & Distribution
        salesDistribution: "المبيعات والتوزيع",
        hitRate: "معدل النجاح",
        otif: "التسليم في الوقت المحدد",
        creditHold: "إيقاف الائتمان",
        returns: "المرتجعات",
        quotations: "عروض الأسعار",
        orders: "الطلبات",
        deliveries: "التسليمات",
        services: "الخدمات",

        // Manufacturing
        manufacturing: "التصنيع والإنتاج",
        activeProduction: "الإنتاج النشط",
        avgYield: "متوسط الإنتاجية",
        availableWorkCenters: "مراكز العمل المتاحة",
        variancesPending: "الانحرافات المعلقة",
        productionOrders: "أوامر الإنتاج",
        boms: "قوائم المواد",
        routings: "مسارات الإنتاج",
        workCenters: "مراكز العمل",
        variances: "الانحرافات",
        standardCosts: "التكاليف المعيارية",

        // Quality Management
        qualityManagement: "إدارة الجودة",
        firstPassYield: "إنتاجية المرة الأولى",
        rejectedLots: "الدفعات المرفوضة",
        openNCs: "عدم المطابقة المفتوحة",
        coasIssued: "شهادات التحليل الصادرة",
        inspectionLots: "دفعات الفحص",
        nonConformances: "عدم المطابقة",
        coas: "شهادات التحليل",
        qcPlans: "خطط مراقبة الجودة",

        // Procurement
        procurement: "المشتريات",
        pendingPRs: "طلبات الشراء المعلقة",
        activePOs: "أوامر الشراء النشطة",
        totalSpend: "إجمالي الإنفاق",
        pendingMatches: "المطابقات المعلقة",
        requisitions: "طلبات الشراء",
        rfqs: "طلبات عروض الأسعار",
        pos: "أوامر الشراء",
        grns: "إشعارات الاستلام",
        vendorInvoices: "فواتير الموردين",

        // Maintenance Management
        maintenanceManagement: "إدارة الصيانة",
        openWorkOrders: "أوامر العمل المفتوحة",
        pmCompliance: "الالتزام بالصيانة الوقائية",
        mttr: "متوسط وقت الإصلاح",
        criticalDown: "المعدات الحرجة المتوقفة",
        lowStockParts: "قطع الغيار منخفضة المخزون",
        totalCost: "التكلفة الإجمالية",
        workOrders: "أوامر العمل",
        pmPlans: "خطط الصيانة الوقائية",
        equipment: "المعدات",
        spareParts: "قطع الغيار",
        downtimes: "فترات التوقف",
        consumptions: "الاستهلاك",

        // Finance & Accounting
        financeAccounting: "المالية والمحاسبة",
        totalAROutstanding: "إجمالي الذمم المدينة",
        totalAPOutstanding: "إجمالي الذمم الدائنة",
        overdueAR: "الذمم المتأخرة",
        fixedAssetsNBV: "صافي قيمة الأصول الثابتة",
        gl: "دفتر الأستاذ",
        ar: "الذمم المدينة",
        ap: "الذمم الدائنة",
        cashBank: "النقد/البنك",

        // HR & Payroll
        hrPayrollKSA: "الموارد البشرية والرواتب (السعودية)",
        activeEmployees: "الموظفون النشطون",
        saudizationRate: "نسبة السعودة",
        pendingLeaves: "طلبات الإجازة المعلقة",
        activeLoans: "القروض النشطة",
        employees: "الموظفون",
        leaves: "طلبات الإجازة",
        payroll: "الرواتب",
        loansAdvances: "القروض/السلف",
        endOfService: "نهاية الخدمة",

        // Analytics specific
        analyticsBI: "ذكاء الأعمال والتحليلات",
        kpisDashboardsInsights: "مؤشرات الأداء ولوحات المعلومات والرؤى",
        dateRange: "النطاق الزمني",
        branch: "الفرع",
        last7Days: "آخر 7 أيام",
        last30Days: "آخر 30 يوم",
        last90Days: "آخر 90 يوم",
        ytd: "من بداية العام",
        lastYear: "العام الماضي",
        allBranches: "جميع الفروع",
        riyadh: "الرياض",
        jeddah: "جدة",
        dammam: "الدمام",
        executive: "التنفيذي",
        totalRevenue: "إجمالي الإيرادات",
        grossProfit: "إجمالي الربح",
        stockValue: "قيمة المخزون",
        margin: "الهامش",
        turnover: "دوران",
        efficiency: "الكفاءة",
        dso: "DSO (أيام)",
        dsoFull: "أيام المبيعات المستحقة",
        dpo: "DPO (أيام)",
        dpoFull: "أيام الدفعات المستحقة",
        qualityRate: "معدل الجودة",
        saudization: "السعودة",
        saudi: "سعودي",
        revenueTrend: "اتجاه الإيرادات (آخر 6 أشهر)",
        topProductsByRevenue: "أفضل 5 منتجات حسب الإيرادات",
        inventoryAging: "تقادم المخزون",
        arAgingAnalysis: "تحليل تقادم الذمم المدينة",
        totalOrders: "إجمالي الطلبات",
        avgOrderValue: "متوسط قيمة الطلب",
        perOrder: "لكل طلب",
        pendingOrders: "الطلبات المعلقة",
        awaitingConfirmation: "في انتظار التأكيد",
        delivered: "تم التسليم",
        completedOrders: "الطلبات المكتملة",
        salesByMonth: "المبيعات حسب الشهر",
        salesByStatus: "المبيعات حسب الحالة",
        count: "العدد",
        unitsSold: "وحدة مباعة",
        totalStockValue: "إجمالي قيمة المخزون",
        items: "عناصر",
        stockTurnover: "دوران المخزون",
        annualTurnover: "الدوران السنوي",
        slowMoving: "بطيء الحركة",
        over90Days: ">90 يوم",
        lowStockItems: "عناصر منخفضة المخزون",
        needReorder: "تحتاج إعادة طلب",
        inventoryAgingDistribution: "توزيع تقادم المخزون",
        stockValueByCategory: "قيمة المخزون حسب الفئة",
        value: "القيمة",
        productionEfficiency: "كفاءة الإنتاج",
        outputVsPlanned: "الإنتاج مقابل المخطط",
        totalProduced: "إجمالي الإنتاج",
        units: "وحدات",
        productionByStatus: "الإنتاج حسب الحالة",
        productionQuantityByProduct: "كمية الإنتاج حسب المنتج",
        totalPurchases: "إجمالي المشتريات",
        avgPOValue: "متوسط قيمة أمر الشراء",
        perPO: "لكل أمر شراء",
        payableOutstanding: "المستحقات الدائنة",
        pendingPOs: "أوامر الشراء المعلقة",
        awaitingApproval: "في انتظار الموافقة",
        purchaseByVendor: "المشتريات حسب المورد",
        apAging: "تقادم الذمم الدائنة",
        salesOutstanding: "المبيعات المستحقة",
        revenueVsCosts: "الإيرادات مقابل التكاليف",
        costs: "التكاليف",
        profit: "الربح",
        arVsAp: "الذمم المدينة مقابل الدائنة",
        accountsReceivable: "الذمم المدينة",
        accountsPayable: "الذمم الدائنة",
        cashFlowIndicators: "مؤشرات التدفق النقدي",
        workingCapital: "رأس المال العامل",
        cashConversionCycle: "دورة تحويل النقد",
        days: "أيام",
        currentRatio: "النسبة الجارية",
        quickRatio: "النسبة السريعة",
        projectMargin: "هامش المشروع",
        grossMargin: "الهامش الإجمالي",
        employeesByDepartment: "الموظفون حسب القسم",
        nationalityDistribution: "توزيع الجنسيات",
        nonSaudi: "غير سعودي",
        projectPerformance: "أداء المشاريع",
        complete: "مكتمل",
        
        // Projects & Services
        newProject: "مشروع جديد",
        newTask: "مهمة جديدة",
        newTimesheet: "جدول عمل جديد",
        newExpense: "مصروف جديد",
        newMilestone: "معلم جديد",
        resourceAllocations: "تخصيص الموارد",
        projectExpenses: "مصروفات المشاريع",
        projectMilestones: "معالم المشاريع",
        projectTasks: "مهام المشاريع",
        allocateResource: "تخصيص مورد",
        bulkAllocate: "تخصيص جماعي",
        
        // AI Assistant
        aiAssistantAnalytics: "المساعد الذكي والتحليلات",
        aiInsightsDesc: "احصل على رؤى، اطرح أسئلة، ودع الذكاء الاصطناعي يساعدك في إدارة أعمالك",
        chatAssistant: "المساعد الذكي",
        aiInsights: "رؤى الذكاء الاصطناعي",
        newChat: "محادثة جديدة",
        erpAssistant: "مساعد تخطيط موارد المؤسسات",
        messages: "رسائل",
        howCanIHelp: "كيف يمكنني مساعدتك اليوم؟",
        askMeAnything: "اسألني أي شيء عن بيانات عملك أو التقارير أو دعني أساعدك في إنشاء وإدارة السجلات.",
        showSalesPerformance: "عرض أداء المبيعات",
        checkInventoryLevels: "التحقق من مستويات المخزون",
        viewPendingApprovals: "عرض الموافقات المعلقة",
        askAnything: "اسألني أي شيء عن عملك...",
        noConversationSelected: "لم يتم تحديد محادثة",
        createChatToStart: "أنشئ محادثة جديدة للبدء",
        startNewChat: "بدء محادثة جديدة",
        
        // KPI Dashboard
        kpiDashboard: "لوحة مؤشرات الأداء",
        trackMonitorKPIs: "تتبع ومراقبة مؤشرات الأداء الرئيسية",
        addKPI: "إضافة مؤشر أداء",
        onTarget: "على المسار الصحيح",
        atRisk: "معرض للخطر",
        offTarget: "خارج المسار",
        avgAchievement: "متوسط الإنجاز",
        ofKPIs: "من مؤشرات الأداء",
        needsAttention: "يحتاج انتباه",
        requiresAction: "يتطلب إجراء",
        overallPerformance: "الأداء الإجمالي",
        allKPIs: "جميع مؤشرات الأداء",
        allCategories: "جميع الفئات",
        financialKPIs: "مؤشرات الأداء المالية",
        operationalKPIs: "مؤشرات الأداء التشغيلية",
        customerKPIs: "مؤشرات أداء العملاء",
        employeeKPIs: "مؤشرات أداء الموظفين",
        qualityKPIs: "مؤشرات أداء الجودة",
        supplyChainKPIs: "مؤشرات أداء سلسلة الإمداد",
        kpiName: "اسم مؤشر الأداء",
        category: "الفئة",
        owner: "المسؤول",
        target: "الهدف",
        actual: "الفعلي",
        achievement: "الإنجاز",
        trend: "الاتجاه",
        updateFreq: "تكرار التحديث",
        
        // Master Data Management
        masterDataMgmt: "إدارة البيانات الرئيسية",
        manageMasterData: "إدارة المواد والعملاء والموردين ومندوبي المبيعات والتسلسلات الهرمية",
        refreshAll: "تحديث الكل",
        totalMaterials: "إجمالي المواد",
        groups: "مجموعات",
        totalCustomers: "إجمالي العملاء",
        salesmen: "مندوبي المبيعات",
        unitConversions: "تحويلات الوحدات",
        multiUOM: "متعدد وحدات القياس",
        materialsItems: "دليل المواد والأصناف",
        template: "نموذج",
        excelUpload: "رفع ملف إكسل",
        newMaterial: "مادة جديدة",
        customerMaster: "دليل العملاء (مرتبط بمندوب المبيعات)",
        newCustomer: "عميل جديد",
        vendorMaster: "دليل الموردين",
        newVendor: "مورد جديد",
        salesmenMaster: "دليل مندوبي المبيعات",
        newSalesman: "مندوب مبيعات جديد",
        materialGroups: "مجموعات المواد",
        newGroup: "مجموعة جديدة",
        materialSubGroups: "المجموعات الفرعية للمواد",
        newSubGroup: "مجموعة فرعية جديدة",
        unitConversionsTitle: "تحويلات الوحدات (قطع ↔ حزمة ↔ أطنان)",
        newConversion: "تحويل جديد",
        
        // Coil Management
        coilManagementSlitting: "إدارة اللفائف والتقطيع",
        trackCoilsDesc: "تتبع وإدارة لفائف المواد الخام وعمليات التقطيع",
        totalCoils: "إجمالي اللفائف",
        allRegisteredCoils: "جميع اللفائف المسجلة",
        available: "متاح",
        readyToUse: "جاهز للاستخدام",
        totalWeight: "الوزن الإجمالي",
        currentStock: "المخزون الحالي",
        reserved: "محجوز",
        forProduction: "للإنتاج",
        qcPending: "فحص الجودة معلق",
        awaitingInspection: "في انتظار الفحص",
        coilInventory: "مخزون اللفائف",
        slittingOperations: "عمليات التقطيع",
        history: "السجل",
        slitCoil: "تقطيع لفافة",
        registerCoil: "تسجيل لفافة",
        coilHistory: "سجل وتتبع اللفائف",
        
        // Supply Chain
        supplyChainMgmt: "إدارة سلسلة الإمداد",
        endToEndVisibility: "رؤية شاملة لتدفق المواد والمنتجات",
        procurement: "المشتريات",
        distribution: "التوزيع",
        recentPurchaseOrders: "أوامر الشراء الأخيرة",
        recentSalesOrders: "أوامر المبيعات الأخيرة",
        
        // Costing
        costManagement: "إدارة التكاليف",
        productCostingDesc: "تكلفة المنتج، تحليل الانحرافات وتكلفة المشاريع",
        activeProductCosts: "تكاليف المنتجات النشطة",
        avgCost: "متوسط",
        unit: "وحدة",
        totalActualCosts: "إجمالي التكاليف الفعلية",
        costRecords: "سجلات التكلفة",
        unfavorableVariances: "الانحرافات غير المواتية",
        averageMargin: "متوسط الهامش",
        acrossProducts: "عبر",
        products: "منتجات",
        productCosts: "تكاليف المنتجات",
        actualCosts: "التكاليف الفعلية",
        costPools: "مجمعات التكاليف",
        overheadRates: "معدلات التكاليف العامة",
        jobCosts: "تكاليف المشاريع",
        productCosting: "تكلفة المنتج",
        calculateProductCost: "حساب تكلفة المنتج",
        actualCostRecords: "سجلات التكاليف الفعلية",
        costVarianceAnalysis: "تحليل انحرافات التكلفة",
        newCostPool: "مجمع تكاليف جديد",
        newOverheadRate: "معدل تكاليف عامة جديد",
        jobCosting: "تكلفة المشاريع",
        
        // Treasury Management
        treasuryMgmt: "إدارة الخزينة",
        cashFlowForecastingDesc: "التنبؤ بالتدفق النقدي وإدارة السيولة",
        
        // Asset Lifecycle
        assetLifecycleMgmt: "إدارة دورة حياة الأصول",
        trackAssetDisposalDesc: "تتبع التخلص من الأصول والتقاعد والعائد على الاستثمار وتحليلات دورة الحياة",
        exportCSV: "تصدير CSV",
        printReport: "طباعة التقرير",
        filters: "التصفيات",
        reset: "إعادة تعيين",
        assetClass: "فئة الأصل",
        allClasses: "جميع الفئات",
        machinery: "آلات",
        equipment: "معدات",
        vehicles: "مركبات",
        computers: "حواسيب",
        furniture: "أثاث",
        disposalType: "نوع التخلص",
        allTypes: "جميع الأنواع",
        sale: "بيع",
        scrap: "خردة",
        donation: "تبرع",
        tradeIn: "مبادلة",
        writeOff: "شطب",
        dateFrom: "من تاريخ",
        dateTo: "إلى تاريخ",
        yearFrom: "من سنة",
        yearTo: "إلى سنة",
        activeAssets: "الأصول النشطة",
        currentlyInUse: "قيد الاستخدام حاليًا",
        disposedAssets: "الأصول المتخلص منها",
        pendingApproval: "في انتظار الموافقة",
        disposalValue: "قيمة التخلص",
        transactions: "معاملات",
        totalGainLoss: "إجمالي الربح/الخسارة",
        netGain: "ربح صافي",
        netLoss: "خسارة صافية",
        averageROI: "متوسط العائد على الاستثمار",
        onDisposedAssets: "على الأصول المتخلص منها",
        byType: "حسب النوع",
        byYear: "حسب السنة",
        roiAnalysis: "تحليل العائد على الاستثمار",
        lifecycle: "دورة الحياة",
        details: "التفاصيل",
        disposalByType: "التخلص حسب النوع",
        breakdown: "التفصيل",
        assets: "أصول",
        disposalTrend: "اتجاه التخلص حسب السنة",
        roiDistribution: "توزيع العائد على الاستثمار",
        roiCategories: "فئات العائد على الاستثمار",
        assetAgeVsMaintenance: "عمر الأصل مقابل تكلفة الصيانة",
        insights: "الرؤى",
        disposalTransactions: "معاملات التخلص",
        
        // Approval Workflows
        approvalWorkflowConfig: "تكوين سير عمل الموافقات",
        configureMultiLevelDesc: "تكوين سلاسل الموافقات متعددة المستويات للمستندات التجارية",
        workflowBuilder: "منشئ سير العمل",
        allRules: "جميع القواعد",
        configureNewWorkflow: "تكوين سير عمل جديد",
        newRule: "قاعدة جديدة",
        allApprovalMatrixRules: "جميع قواعد مصفوفة الموافقات",
        documentType: "نوع المستند",
        amountRange: "نطاق المبلغ (ريال)",
        level: "المستوى",
        requiredRole: "الدور المطلوب",
        settings: "الإعدادات",
        mandatory: "إلزامي",
        parallel: "متوازي",
        notify: "إشعار",
        approvalLevels: "مستويات الموافقة",
        
        // HR
        hr: "الموارد البشرية",
        
        // Additional common terms
        overview: "نظرة عامة",
        financial: "مالي",
        operational: "تشغيلي",
        employee: "موظف",
        
        // Manufacturing & Production (additional)
        bomItems: "عناصر قائمة المواد",
        operations: "العمليات",
        materialIssue: "إصدار المواد",
        productionConfirmation: "تأكيد الإنتاج",
        
        // Demand Planning
        forecastAccuracy: "دقة التنبؤ",
        demandForecast: "التنبؤ بالطلب",
        forecastMethod: "طريقة التنبؤ",
        forecastedQuantity: "الكمية المتوقعة",
        actualDemand: "الطلب الفعلي",
        
        // Treasury Management (additional)
        cashPosition: "الوضع النقدي",
        cashFlowForecast: "التنبؤ بالتدفق النقدي",
        liquidityRatio: "نسبة السيولة",
        inflows: "التدفقات الداخلة",
        outflows: "التدفقات الخارجة",
        
        // Depreciation Reports (additional)
        depreciationSchedule: "جدول الإهلاك",
        assetRegister: "سجل الأصول",
        monthlyDepreciation: "الإهلاك الشهري",
        yearlyDepreciation: "الإهلاك السنوي",
        
        // HR & Payroll (additional)
        payslip: "قسيمة الراتب",
        attendanceRegister: "سجل الحضور",
        leaveBalance: "رصيد الإجازات",
        endOfServiceBenefit: "مكافأة نهاية الخدمة",
        wps: "نظام حماية الأجور",
        gosi: "التأمينات الاجتماعية",
        
        // ZATCA (additional)
        zatcaCompliant: "متوافق مع هيئة الزكاة",
        einvoicing: "الفوترة الإلكترونية",
        qrCode: "رمز الاستجابة السريعة",
        submissionStatus: "حالة الإرسال",
        clearanceStatus: "حالة المقاصة"
    }
};

export const LanguageProvider = ({ children }) => {
    const [language, setLanguage] = useState(() => {
        if (typeof window !== 'undefined') {
            return localStorage.getItem('appLanguage') || 'en';
        }
        return 'en';
    });

    const isRTL = language === 'ar';

    useEffect(() => {
        if (typeof window === 'undefined') return;
        
        localStorage.setItem('appLanguage', language);
        document.documentElement.setAttribute('dir', isRTL ? 'rtl' : 'ltr');
        document.documentElement.setAttribute('lang', language);
        
        if (isRTL) {
            document.body.classList.add('rtl');
        } else {
            document.body.classList.remove('rtl');
        }
    }, [language, isRTL]);

    const toggleLanguage = () => {
        setLanguage(prev => prev === 'en' ? 'ar' : 'en');
    };

    const t = (key) => {
        return translations[language][key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, isRTL, toggleLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
};

export default LanguageContext;
